name: Build Check

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: update apt-get 
      run:  sudo apt-get update

    - name: checkout
      uses: actions/checkout@v3

    - name: build
      run: make
